server.port=8080
mybatis.config-location=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=/mapper/*.xml
spring.thymeleaf.cache=true
spring.servlet.multipart.max-file-size=3MB

#####################################################################################################
###################################### mysql数据库连接配置 ############################################
#####################################################################################################
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/forum-java?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true&allowPublicKeyRetrieval=true
spring.datasource.username=
spring.datasource.password=

#####################################################################################################
###################################### 发送163邮件相关配置，可为空 #####################################
#####################################################################################################
custom-config.mail.smtp.host=smtp.163.com
custom-config.mail.smtp.port=465
custom-config.mail.smtp.socketFactoryPort=465
custom-config.mail.smtp.auth=true
custom-config.mail.smtp.account=15620608572@163.com
custom-config.mail.smtp.password=account login password
custom-config.mail.smtp.fromAddress=开发者社区 <15620608572@163.com>

#####################################################################################################
###################################### 七牛云相关配置，必填：文件上传使用 ################################
#####################################################################################################
custom-config.upload-file.qiniu.accessKey=
custom-config.upload-file.qiniu.secretKey=
custom-config.upload-file.qiniu.bucketName=
# 访问域名，例如 https://static.developers.pub/
custom-config.upload-file.qiniu.accessDomain=

#####################################################################################################
###################################### 页面自定义展示配置 ##############################################
#####################################################################################################
# 全局页面配置 =》网站名称
custom-config.view.global.websiteName=开发者客栈
# 全局页面配置 =》网站 logo url
custom-config.view.global.websiteLogoUrl=https://static.developers.pub/logo.jpeg
# 全局页面配置 =》网站 favicon icon url
custom-config.view.global.websiteFaviconIconUrl=https://static.developers.pub/favicon.ico
# 全局页面配置 =》联系我 wx qr code img url，不配置 contactMeWxQrCode 时不现实
custom-config.view.global.contactMeTitle=联系我 - 作者微信
custom-config.view.global.contactMeWxQrCode=https://static.developers.pub/70f707281f5d40b49c9e703aa70d002a
# 全局页面配置 =》分页大小
custom-config.view.global.pageSize=20
# 全局页面配置 =》图片访问时样式，访问cdn图片时，可自定义压缩格式 => ?imageView2/2/w/700
custom-config.view.global.cdnImgStyle=
# 首页侧边栏类型 names
custom-config.view.index-page.sidebar-type-names=公告,活动
# 全局页面配置 =》页面底部网站建站年份
custom-config.view.global.websiteStartYear=2016
# 全局页面配置 =》页面底部网站备案号
custom-config.view.global.websiteRecord=蜀ICP备17014120号

#####################################################################################################
###################################### github 登录授权使用 #####################################
#####################################################################################################
# github 授权登录 client id
custom-config.view.global.githubClientId=
# github 授权登录 client secret
custom-config.oauth.github.clientSecret=

#####################################################################################################
###################################### Jasypt 加密配置 #####################################
#####################################################################################################
jasypt.encryptor.password=your-secret-key
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator